# GENERATED active theme: ypsilon-auto (via gen-theme.py --theme)
general {
    col.active_border = rgba(876dd5dd)
    col.inactive_border = rgba(a29db422)
}
decoration {
    shadow {
        color = rgba(0d0b1373)
    }
}
