#!/usr/bin/env python3
"""Ypsilon theme generator.

Reads themes/tokens.json (single source of truth) and writes:
  hypr/themes/<name>.conf      per-theme Hyprland color overrides
  hypr/themes/current.conf     active theme (sourced LAST by hypr/ypsilon.conf)
  shell/style/_generated.css   AGS theme overrides (loaded after style.scss)

Local build tool. Never touches ~/.config. Safe to run anytime.

Usage:
  gen-theme.py --list
  gen-theme.py                 regenerate all using current active theme
  gen-theme.py --theme NAME    set active theme + regenerate
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOKENS = os.path.join(ROOT, "themes", "tokens.json")
HYPR_DIR = os.path.join(ROOT, "hypr", "themes")
CSS_OUT = os.path.join(ROOT, "shell", "style", "_generated.css")


def load_tokens():
    with open(TOKENS) as f:
        return json.load(f)


def save_tokens(tokens):
    with open(TOKENS, "w") as f:
        json.dump(tokens, f, indent=2)
        f.write("\n")


def hypr_color(hexstr, alpha="ff"):
    """'#rrggbb' -> 'rgba(rrggbbaa)' (Hyprland format)."""
    h = hexstr.lstrip("#")
    if len(h) == 6:
        h = h + alpha
    return "rgba(%s)" % h


def hex_rgba(hexstr, alpha):
    """'#rrggbb' + 0..1 -> 'rgba(r, g, b, a)' (GTK-safe)."""
    h = hexstr.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return "rgba(%d, %d, %d, %s)" % (r, g, b, alpha)


def theme_hypr(name, t):
    active = hypr_color(t["primary"], "ee") + " " + hypr_color(t["accent"], "ee") + " 45deg"
    return (
        "# GENERATED by scripts/gen-theme.py — do not edit. Theme: %s\n"
        "general {\n"
        "    col.active_border = %s\n"
        "    col.inactive_border = %s\n"
        "}\n"
        "decoration {\n"
        "    col.shadow = %s\n"
        "}\n" % (name, active, hypr_color(t["muted"], "55"), hypr_color(t["bg"], "73"))
    )


def theme_css(name, t, tokens):
    radius = tokens.get("radius", {}).get("md", 18)
    return (
        "/* GENERATED by scripts/gen-theme.py — do not edit. Theme: %s */\n"
        ".bar-inner {\n"
        "  background: %s;\n"
        "  border-color: %s;\n"
        "  border-radius: %dpx;\n"
        "}\n"
        ".clock, .media-title, .notif-summary, .launcher-title,\n"
        ".control-title, .osd-label, .power-title, .overview-title {\n"
        "  color: %s;\n"
        "}\n"
        ".status-sub, .notif-body,\n"
        ".launcher-sub, .control-sub, .tray-empty {\n"
        "  color: %s;\n"
        "}\n"
        ".launch-btn, .power-btn, .pill-btn, .ws-btn {\n"
        "  background: %s;\n"
        "  border-color: %s;\n"
        "  color: %s;\n"
        "}\n"
        ".launch-btn:hover, .power-btn:hover, .pill-btn:hover, .ws-btn:hover {\n"
        "  background: %s;\n"
        "}\n"
        ".ws-btn.active {\n"
        "  background: %s;\n"
        "  color: %s;\n"
        "  border-color: %s;\n"
        "}\n"
        ".accent {\n"
        "  color: %s;\n"
        "}\n"
        ".good { color: %s; }\n"
        ".warn { color: %s; }\n"
        ".bad { color: %s; }\n"
        "window.ypsilon-launcher .launcher-inner,\n"
        "window.ypsilon-control .control-inner,\n"
        "window.ypsilon-notif-center .notif-center-inner,\n"
        "window.ypsilon-toast .toast-inner,\n"
        "window.ypsilon-osd .osd-inner,\n"
        "window.ypsilon-power .power-inner,\n"
        "window.ypsilon-overview .overview-inner {\n"
        "  background: %s;\n"
        "  border-color: %s;\n"
        "  color: %s;\n"
        "}\n"
        ".entry {\n"
        "  background: %s;\n"
        "  border-color: %s;\n"
        "  color: %s;\n"
        "}\n" % (
            name,
            t["surface"], t["border"], radius,
            t["fg"],
            t["muted"],
            hex_rgba(t["primary"], 0.18), t["border"], t["fg"],
            hex_rgba(t["primary"], 0.38),
            t["primary"], t["bg"], t["primary"],
            t["accent"],
            t["good"], t["warn"], t["bad"],
            t["surface"].replace("0.72", "0.85") if "0.72" in t["surface"] else t["surface"],
            t["border"], t["fg"],
            t["bg_alt"], t["border"], t["fg"],
        )
    )


EXTRA_DIR = os.path.join(ROOT, "extras")


def nohash(hexstr):
    return hexstr.lstrip("#")


def extras(name, t):
    """Terminal/launcher/GTK theme files. Symlink or copy these when daily-driving."""
    ansi = t.get("ansi", ["#000000"] * 16)
    lines = []
    lines.append(("# GENERATED by scripts/gen-theme.py — theme: %s. " % name) + "Copy, don't symlink blindly; check target app first.")
    out = {}

    foot = list(lines) + ["", "[colors]", "background=%s" % nohash(t["bg"]), "foreground=%s" % nohash(t["fg"])]
    for i in range(8):
        foot.append("regular%d=%s" % (i, nohash(ansi[i])))
    for i in range(8):
        foot.append("bright%d=%s" % (i, nohash(ansi[i + 8])))
    out["foot-%s.ini" % name] = "\n".join(foot) + "\n"

    kitty = list(lines) + ["", "background %s" % t["bg"], "foreground %s" % t["fg"], "cursor %s" % t["primary"]]
    for i, c in enumerate(ansi):
        kitty.append("color%d %s" % (i, c))
    out["kitty-%s.conf" % name] = "\n".join(kitty) + "\n"

    ghostty = list(lines) + ["", "background = %s" % t["bg"], "foreground = %s" % t["fg"]]
    for i, c in enumerate(ansi):
        ghostty.append("palette = %d=%s" % (i, c))
    out["ghostty-%s" % name] = "\n".join(ghostty) + "\n"

    fuzzel = list(lines) + ["", "[colors]", "background=%sb8" % nohash(t["bg"]), "text=%sff" % nohash(t["fg"]),
                            "match=%sff" % nohash(t["primary"]), "selection=%s66" % nohash(t["primary"]),
                            "selection-text=%sff" % nohash(t["fg"]), "selection-match=%sff" % nohash(t["accent"]),
                            "border=%sff" % nohash(t["primary"])]
    out["fuzzel-%s.ini" % name] = "\n".join(fuzzel) + "\n"

    gtk = [lines[0], "",
           "@define-color y_bg %s;" % t["bg"], "@define-color y_bg_alt %s;" % t["bg_alt"],
           "@define-color y_fg %s;" % t["fg"], "@define-color y_muted %s;" % t["muted"],
           "@define-color y_primary %s;" % t["primary"], "@define-color y_accent %s;" % t["accent"],
           "@define-color y_good %s;" % t["good"], "@define-color y_warn %s;" % t["warn"],
           "@define-color y_bad %s;" % t["bad"]]
    out["gtk-%s.css" % name] = "\n".join(gtk) + "\n"

    os.makedirs(EXTRA_DIR, exist_ok=True)
    for fname, text in out.items():
        with open(os.path.join(EXTRA_DIR, fname), "w") as f:
            f.write(text)


def regenerate(active):
    tokens = load_tokens()
    themes = tokens["themes"]
    if active not in themes:
        print("unknown theme: %s (available: %s)" % (active, ", ".join(sorted(themes))))
        return 1
    os.makedirs(HYPR_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(CSS_OUT), exist_ok=True)
    for name, t in sorted(themes.items()):
        with open(os.path.join(HYPR_DIR, "%s.conf" % name), "w") as f:
            f.write(theme_hypr(name, t))
        extras(name, t)
    with open(os.path.join(HYPR_DIR, "current.conf"), "w") as f:
        f.write("# GENERATED active theme: %s (via gen-theme.py --theme)\n" % active)
        f.write(theme_hypr(active, themes[active]).split("\n", 1)[1])
    with open(CSS_OUT, "w") as f:
        f.write(theme_css(active, themes[active], tokens))
    print("generated: %d hypr themes + current.conf (%s) + _generated.css" % (len(themes), active))
    return 0


def main(argv):
    tokens = load_tokens()
    if "--list" in argv:
        print("active:", tokens.get("active"))
        for k in sorted(tokens.get("themes", {})):
            print(" -", k)
        return 0
    if "--theme" in argv:
        i = argv.index("--theme")
        if i + 1 >= len(argv):
            print("usage: gen-theme.py --theme NAME")
            return 1
        tokens["active"] = argv[i + 1]
        save_tokens(tokens)
    return regenerate(tokens.get("active", "ypsilon-dark"))


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
