#!/usr/bin/env python3
"""Ypsilon theme generator.

Reads themes/tokens.json (single source of truth) and writes:
  hypr/themes/<name>.conf      per-theme Hyprland color overrides
  hypr/themes/current.conf     active theme (sourced LAST by hypr/ypsilon.conf)
  hypr/themes/lock-current.conf  hyprlock color variables for the active theme
  shell/style/_generated.css   AGS theme overrides (named colors used by style.css)

Local build tool. Never touches ~/.config. Safe to run anytime.

Usage:
  gen-theme.py --list
  gen-theme.py                 regenerate all using current active theme
  gen-theme.py --theme NAME    set active theme + regenerate
  gen-theme.py --paths-only    only hypr/generated/* (repo path baked into hypr configs)
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOKENS = os.path.join(ROOT, "themes", "tokens.json")
HYPR_DIR = os.path.join(ROOT, "hypr", "themes")
CSS_OUT = os.path.join(ROOT, "shell", "style", "_generated.css")


USER_THEMES = os.path.join(ROOT, "themes", "user")
REQUIRED = ("bg", "bg_alt", "fg", "muted", "primary", "accent", "good", "warn", "bad", "surface", "border")


def load_tokens():
    """tokens.json + every themes/user/*.json (e.g. ypsilon-auto from the wallpaper)."""
    with open(TOKENS) as f:
        tokens = json.load(f)
    if os.path.isdir(USER_THEMES):
        for fname in sorted(os.listdir(USER_THEMES)):
            if not fname.endswith(".json"):
                continue
            try:
                with open(os.path.join(USER_THEMES, fname)) as f:
                    t = json.load(f)
            except (OSError, ValueError) as e:
                print("skip user theme %s: %s" % (fname, e))
                continue
            if all(k in t for k in REQUIRED):
                tokens["themes"][fname[:-5]] = t
                tokens.setdefault("_user_themes", []).append(fname[:-5])
            else:
                print("skip user theme %s: missing %s" % (fname, [k for k in REQUIRED if k not in t]))
    return tokens


def set_active(name):
    """Rewrite only the "active" line so tokens.json keeps its hand formatting."""
    with open(TOKENS) as f:
        text = f.read()
    text, n = re.subn(r'("active"\s*:\s*)"[^"]*"', r'\1"%s"' % name, text, count=1)
    if n != 1:
        raise SystemExit('tokens.json has no "active" key')
    with open(TOKENS, "w") as f:
        f.write(text)


def hypr_color(hexstr, alpha="ff"):
    """'#rrggbb' -> 'rgba(rrggbbaa)' (Hyprland format)."""
    h = hexstr.lstrip("#")
    if len(h) == 6:
        h = h + alpha
    return "rgba(%s)" % h


def hex_rgba(hexstr, alpha):
    """'#rrggbb' + 0..1 -> 'rgba(r, g, b, a)' (GTK-safe)."""
    h = hexstr.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return "rgba(%d, %d, %d, %s)" % (r, g, b, alpha)


def mix(a, b, t):
    """'#rrggbb' a→b by t (0..1) -> '#rrggbb'."""
    ha, hb = a.lstrip("#"), b.lstrip("#")
    ca = [int(ha[i:i + 2], 16) for i in (0, 2, 4)]
    cb = [int(hb[i:i + 2], 16) for i in (0, 2, 4)]
    return "#%02x%02x%02x" % tuple(round(x + (y - x) * t) for x, y in zip(ca, cb))


def on_color(hexstr):
    """Text color for a filled surface: near-black on light fills, near-white on dark ones."""
    h = hexstr.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    lin = [c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in (r, g, b)]
    lum = 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]
    return "#111111" if lum > 0.36 else "#ffffff"


def theme_hypr(name, t):
    # one solid color: a two-hue gradient around every window is the loudest thing on screen
    active = hypr_color(t["primary"], "dd")
    return (
        "# GENERATED by scripts/gen-theme.py — do not edit. Theme: %s\n"
        "general {\n"
        "    col.active_border = %s\n"
        "    col.inactive_border = %s\n"
        "}\n"
        "decoration {\n"
        "    shadow {\n"
        "        color = %s\n"
        "    }\n"
        "}\n" % (name, active, hypr_color(t["muted"], "22"), hypr_color(t["bg"], "73"))
    )


def theme_lock(name, t):
    """hyprlock color variables (sourced by hypr/hyprlock.conf)."""
    def c(key, a):
        return hypr_color(t[key], a)
    return (
        "# GENERATED by scripts/gen-theme.py — do not edit. Theme: %s\n"
        "$y_fg = %s\n$y_muted = %s\n$y_field = %s\n$y_ring = %s\n$y_ok = %s\n$y_bad = %s\n$y_check = %s\n"
        % (name, c("fg", "ff"), c("muted", "ff"), c("bg_alt", "b8"), c("primary", "cc"), c("good", "ff"), c("bad", "ff"), c("warn", "ff"))
    )


def theme_css(name, t, tokens):
    """Named colors (@y_*) consumed by shell/style.css, plus radius overrides.

    Alpha variants are precomputed here so the CSS never needs alpha().
    """
    r = tokens.get("radius", {})
    op = tokens.get("opacity", {})
    # Material-style roles: surfaces are NEUTRAL layers (the text color at low alpha over the
    # background), the primary color only marks what is on/selected. Tinting every surface with
    # the primary is what made everything look like one red smear.
    fg, primary = t["fg"], t["primary"]
    container = mix(t["bg_alt"], primary, 0.30)
    colors = [
        ("y_bg", t["bg"]), ("y_bg_alt", t["bg_alt"]),
        ("y_fg", fg), ("y_muted", t["muted"]),
        ("y_primary", primary), ("y_accent", t["accent"]),
        ("y_on_primary", on_color(primary)),
        ("y_primary_container", container),
        ("y_on_primary_container", mix(fg, primary, 0.25)),
        ("y_good", t["good"]), ("y_warn", t["warn"]), ("y_bad", t["bad"]),
        ("y_surface", hex_rgba(t["bg"], op.get("bar", 0.86))),
        ("y_popup", hex_rgba(mix(t["bg"], t["bg_alt"], 0.6), op.get("popup", 0.94))),
        ("y_border", hex_rgba(fg, 0.07)),
        ("y_faint", hex_rgba(fg, 0.045)),
        ("y_soft", hex_rgba(fg, 0.08)),
        ("y_hover", hex_rgba(fg, 0.12)),
        ("y_strong", hex_rgba(fg, 0.16)),
        ("y_primary_soft", hex_rgba(primary, 0.16)),
    ]
    out = ["/* GENERATED by scripts/gen-theme.py — do not edit. Theme: %s */" % name]
    out += ["@define-color %s %s;" % (k, v) for k, v in colors]
    out += [
        ".bar-inner { border-radius: %dpx; }" % r.get("md", 18),
        ".popup-card { border-radius: %dpx; }" % r.get("lg", 24),
    ]
    return "\n".join(out) + "\n"


EXTRA_DIR = os.path.join(ROOT, "extras")


def nohash(hexstr):
    return hexstr.lstrip("#")


def extras(name, t, outdir=None, plain_names=False):
    """Terminal/launcher/GTK theme files. Symlink or copy these when daily-driving."""
    ansi = t.get("ansi", ["#000000"] * 16)
    lines = []
    lines.append(("# GENERATED by scripts/gen-theme.py — theme: %s. " % name) + "Copy, don't symlink blindly; check target app first.")
    out = {}

    foot = list(lines) + ["", "[colors]", "background=%s" % nohash(t["bg"]), "foreground=%s" % nohash(t["fg"])]
    for i in range(8):
        foot.append("regular%d=%s" % (i, nohash(ansi[i])))
    for i in range(8):
        foot.append("bright%d=%s" % (i, nohash(ansi[i + 8])))
    out["foot-%s.ini" % name] = "\n".join(foot) + "\n"

    kitty = list(lines) + ["", "background %s" % t["bg"], "foreground %s" % t["fg"], "cursor %s" % t["primary"]]
    for i, c in enumerate(ansi):
        kitty.append("color%d %s" % (i, c))
    out["kitty-%s.conf" % name] = "\n".join(kitty) + "\n"

    ghostty = list(lines) + ["", "background = %s" % t["bg"], "foreground = %s" % t["fg"]]
    for i, c in enumerate(ansi):
        ghostty.append("palette = %d=%s" % (i, c))
    out["ghostty-%s" % name] = "\n".join(ghostty) + "\n"

    fuzzel = list(lines) + ["", "[colors]", "background=%sb8" % nohash(t["bg"]), "text=%sff" % nohash(t["fg"]),
                            "match=%sff" % nohash(t["primary"]), "selection=%s66" % nohash(t["primary"]),
                            "selection-text=%sff" % nohash(t["fg"]), "selection-match=%sff" % nohash(t["accent"]),
                            "border=%sff" % nohash(t["primary"])]
    out["fuzzel-%s.ini" % name] = "\n".join(fuzzel) + "\n"

    gtk = [lines[0], "",
           "@define-color y_bg %s;" % t["bg"], "@define-color y_bg_alt %s;" % t["bg_alt"],
           "@define-color y_fg %s;" % t["fg"], "@define-color y_muted %s;" % t["muted"],
           "@define-color y_primary %s;" % t["primary"], "@define-color y_accent %s;" % t["accent"],
           "@define-color y_good %s;" % t["good"], "@define-color y_warn %s;" % t["warn"],
           "@define-color y_bad %s;" % t["bad"]]
    out["gtk-%s.css" % name] = "\n".join(gtk) + "\n"

    outdir = outdir or EXTRA_DIR
    os.makedirs(outdir, exist_ok=True)
    for fname, text in out.items():
        if plain_names:  # extras/current/kitty.conf etc. — stable paths for your app configs
            fname = fname.replace("-%s" % name, "")
        with open(os.path.join(outdir, fname), "w") as f:
            f.write(text)


def regenerate(active):
    tokens = load_tokens()
    themes = tokens["themes"]
    if active not in themes:
        # e.g. the auto theme file was deleted: never leave the desktop unthemed
        print("theme %s not found — falling back to ypsilon-dark" % active)
        active = "ypsilon-dark"
    os.makedirs(HYPR_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(CSS_OUT), exist_ok=True)
    user = set(tokens.get("_user_themes", []))
    for name, t in sorted(themes.items()):
        if name in user:  # generated per-machine (e.g. from the wallpaper): keep out of git
            continue
        with open(os.path.join(HYPR_DIR, "%s.conf" % name), "w") as f:
            f.write(theme_hypr(name, t))
        extras(name, t)
    # extras/current/*: always the ACTIVE theme under fixed names (gitignored)
    extras(active, themes[active], os.path.join(EXTRA_DIR, "current"), plain_names=True)
    # plain key=#hex for scripts (extras/fish_greeting.fish colours itself with it)
    with open(os.path.join(EXTRA_DIR, "current", "palette.txt"), "w") as f:
        f.write("".join("%s=%s\n" % (k, themes[active][k]) for k in ("primary", "accent", "fg", "muted")))
    with open(os.path.join(HYPR_DIR, "current.conf"), "w") as f:
        f.write("# GENERATED active theme: %s (via gen-theme.py --theme)\n" % active)
        f.write(theme_hypr(active, themes[active]).split("\n", 1)[1])
    with open(os.path.join(HYPR_DIR, "lock-current.conf"), "w") as f:
        f.write(theme_lock(active, themes[active]))
    with open(CSS_OUT, "w") as f:
        f.write(theme_css(active, themes[active], tokens))
    write_generated()
    print("generated: %d hypr themes + current.conf (%s) + _generated.css + hypr/generated/" % (len(themes), active))
    return 0


GEN_DIR = os.path.join(ROOT, "hypr", "generated")


def write_generated():
    """Machine-specific files (gitignored): real repo path baked into hypr configs."""
    os.makedirs(GEN_DIR, exist_ok=True)
    with open(os.path.join(GEN_DIR, "paths.conf"), "w") as f:
        f.write("# GENERATED by scripts/gen-theme.py — repo location, do not edit\n"
                "$YPSILON = %s\n$ypsilon = %s/scripts/ypsilon\nenv = YPSILON_ROOT,%s\n" % (ROOT, ROOT, ROOT))
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import userconf  # config.json -> hypr settings + idle timers
    cfg = userconf.load()
    with open(os.path.join(GEN_DIR, "user.conf"), "w") as f:
        f.write(userconf.render_user_conf(cfg))
    with open(os.path.join(GEN_DIR, "hypridle.conf"), "w") as f:
        f.write(userconf.render_hypridle(cfg, ROOT))
    for name in ("hyprlock.conf",):
        with open(os.path.join(ROOT, "hypr", name)) as f:
            text = f.read().replace("@YPSILON@", ROOT)
        with open(os.path.join(GEN_DIR, name), "w") as f:
            f.write("# GENERATED from hypr/%s by scripts/gen-theme.py — edit the template\n%s" % (name, text))


def main(argv):
    if "--paths-only" in argv:  # hypr/generated/* only; leaves theme outputs untouched
        write_generated()
        return 0
    tokens = load_tokens()
    if "--list" in argv:
        print("active:", tokens.get("active"))
        user = set(tokens.get("_user_themes", []))
        for k in sorted(tokens.get("themes", {})):
            print(" -", k + ("  (user)" if k in user else ""))
        return 0
    if "--theme" in argv:
        i = argv.index("--theme")
        if i + 1 >= len(argv):
            print("usage: gen-theme.py --theme NAME")
            return 1
        if argv[i + 1] not in tokens.get("themes", {}):
            print("unknown theme: %s (available: %s)" % (argv[i + 1], ", ".join(sorted(tokens.get("themes", {})))))
            return 1
        set_active(argv[i + 1])
        tokens = load_tokens()
    return regenerate(tokens.get("active", "ypsilon-dark"))


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
