# Ypsilon — animations: A LOT of effects, but fast. 200-300ms.
animations {
  enabled = true

  bezier = ypsilon, 0.05, 0.9, 0.1, 1.05
  bezier = ypsilonOut, 0.4, 0.0, 0.2, 1.0
  bezier = pop, 0.05, 0.9, 0.1, 1.2

  animation = windows, 1, 4, ypsilon, popin 85%
  animation = windowsOut, 1, 4, ypsilonOut, popin 75%
  animation = windowsMove, 1, 4, ypsilon, slide
  animation = border, 1, 6, default
  animation = fade, 1, 4, default
  animation = workspaces, 1, 4, ypsilon, slidefade 20%
  animation = workspacesIn, 1, 4, ypsilon, slidefade 20%
  animation = workspacesOut, 1, 4, ypsilonOut, slidefade 20%
  animation = specialWorkspace, 1, 4, ypsilon, slidefadevert 15%
  animation = layersIn, 1, 3, pop, popin 90%
  animation = layersOut, 1, 3, ypsilonOut, popin 90%
  animation = fadeLayersIn, 1, 3, default
  animation = fadeLayersOut, 1, 3, default
}
