# Ypsilon — animations: A LOT of effects, but fast. 200-300ms.
animations {
  enabled = true
  first_launch_animation = true

  bezier = ypsilon, 0.05, 0.9, 0.1, 1.05
  bezier = ypsilonOut, 0.4, 0.0, 0.2, 1.0
  bezier = pop, 0.05, 0.9, 0.1, 1.2

  animation = windows, 1, 4, ypsilon, slide
  animation = windowsOut, 1, 4, ypsilonOut, slide
  animation = windowsMove, 1, 4, ypsilon, slide
  animation = border, 1, 6, default
  animation = fade, 1, 4, default
  animation = workspaces, 1, 4, ypsilon, slide
  animation = workspacesIn, 1, 4, ypsilon, slide
  animation = workspacesOut, 1, 4, ypsilonOut, slide
  animation = specialWorkspace, 1, 4, ypsilon, slidevert
  animation = layers, 1, 3, pop, popin 0.9
  animation = layersOut, 1, 3, ypsilonOut, popout 0.9
}
